name: Lint and Static Analysis

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      # Lint JavaScript
      - name: Run ESLint
        uses: sibiraj-s/action-eslint@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore-path: .eslintignore
          ignore-patterns: |
            dist/
            lib/
          extensions: "js,jsx,ts,tsx"
          annotations: true
          package-manager: npm
